services:  
  - type: web
    name: sakakky-elysiajs-tutorial
    runtime: node
    repo: https://github.com/Sakakky-6825/elysia-tutorial
    plan: free
    envVars:
    - key: BUN_VERSION
      value: 1.1.0
    region: oregon
    buildCommand: bun install
    startCommand: bun start
version: "1"
